# --- AWS CONFIG ---
AWS_REGION="eu-west-1"
AWS_ACCESS_KEY_ID="xxxxxxxxxxxxx"
AWS_SECRET_ACCESS_KEY="VRUJ+xxxxxxxxxxxxxxxxxxxx/xxxxxxxxx+xx"
AWS_ACCOUNT_ID="1234567890"

# S3 Bucket
S3_BUCKET_NAME="s3-xxxxxxxxxxxxx"

# Cognito User Pool
COGNITO_USER_POOL_ID="eu-west-1_xxxxxxxxxx"
COGNITO_APP_CLIENT_ID="xxxxxxxxxxxxxxxxxxxxxx"

# ECR Repository Names
ECR_REPO_QUERY="rag-backend-query"
ECR_REPO_INGEST="rag-backend-ingest"

# Lambda Function Names
LAMBDA_FUNC_QUERY="queryLambda"
LAMBDA_FUNC_INGEST="ingestLambda"

# Lambda Endpoints
QUERY_LAMBDA_URL="https://xxxxxxxxxxxxxxxxxxxx.lambda-url.eu-west-1.on.aws/"
INGEST_LAMBDA_URL="https://xxxxxxxxxxxxxxxxxxxxxxxxxx.lambda-url.eu-west-1.on.aws/"

# --- DATABASE (PINECONE) ---
PINECONE_API_KEY="pcsk_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
PINECONE_INDEX_NAME="rag-on-aws-pinecone"

NEO4J_URI="neo4j+s:xxxxxxxxxxxxxxxxxxxxxxxx"
NEO4J_USERNAME="xxxxx"
NEO4J_PASSWORD="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
NEO4J_DATABASE="xxxxx"
AURA_INSTANCEID="xxxxxxx"
AURA_INSTANCENAME="Free instance"

# --- AI MODEL (GEMINI) ---
GOOGLE_API_KEY="AIxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

